language: ruby
rvm:
  - "2.5.3"
  - "2.4.5"
  - "2.3.8"
script: bundle exec rspec spec
addons:
  code_climate:
    repo_token:
      secure: SFpmOHwZ3HBMqMH0NKq0B6DqoQjeDtsr5V9YCRLM7D6LvkoMhbkFYPoNo4nz6EWQ0Ml9JzP7ORumUPv1ujhCcYV+yLQ5eIL/xg+g+3H0Xu1sx6CuzDY4C7mZJO5s84KoH7yu9pBrlIa+UJwezwrCOm7JWURsPhR94YvmKobyOZHEuAyvUbYb+eqAkYfXrl71dC6hywfdlSOP/OEncPpIDZ6EApfWRhqZYHHHoj9EqXuHasNzmr6c2cqAh++7XDIOlHJ8JUEjeZN9ofTrqN4oq4JkGvIVmUHOe62jaj92z4vi3ZH+4lv0GmM5KlxgwRZKcCts5WivaNTyQzUnInUbWlWcIHnBFQMPj17ggjhixb6O+w3uAKlbLUGDYkKRSc+MWEdURpFIhyNCMtesHA1GS9+aU6yuxgz3REJCu7K3s5XkenvqxWucWweCOhNVRYSHhwhXAFO4Atg8ZdgIvGA7gF50TMfvJvQ0UIUvOmCxpVi2dwXDfwCgeks5ghP4Hyf0qXbnkLn3/4CE6khYPjQhb3tDu5AnouzKC3SedVxg9QDKZZYD0XEr7TTB89/LelqDYOjDy1C7/+aLGIi24zgzE7A02W6G8SikX08Er5tUvRw1Fgohkr7Th6YFisIgYqNCyreUeV2co/dhI7lTGk6GrBDqltYPht78EIbto4PVu9s=
